apiVersion : apps/v1
kind: Deployment
metadata:
  name: seokhwanpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seokhwanpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: seokhwanpipelinesjavascriptdocker 
    spec:
      containers:
        - name: seokhwanpipelinesjavascriptdocker 
          image: user110acr.azurecr.io/seokhwanpipelinesjavascriptdocker
          ports:
          - containerPort: 8080